/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerRouteImport } from './routes/_farmer'
import { Route as OfficerRouteImport } from './routes/_officer'
import { Route as OpsRouteImport } from './routes/_ops'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authNoAccessRouteImport } from './routes/(auth)/no-access'
import { Route as authSelectRoleRouteImport } from './routes/(auth)/select-role'
import { Route as authSetPasswordRouteImport } from './routes/(auth)/set-password'
import { Route as FarmerFarmRouteImport } from './routes/_farmer/farm'
import { Route as OfficerOfficerRouteImport } from './routes/_officer/officer'
import { Route as OpsOpsRouteImport } from './routes/_ops/ops'
import { Route as FarmerFarmIndexRouteImport } from './routes/_farmer/farm.index'
import { Route as FarmerFarmMyFarmRouteImport } from './routes/_farmer/farm.my-farm'
import { Route as FarmerFarmOpportunitiesRouteImport } from './routes/_farmer/farm.opportunities'
import { Route as OfficerOfficerIndexRouteImport } from './routes/_officer/officer.index'
import { Route as OfficerOfficerRedeemRouteImport } from './routes/_officer/officer.redeem'
import { Route as OfficerOfficerRegisterRouteImport } from './routes/_officer/officer.register'
import { Route as OfficerOfficerVerifyRouteImport } from './routes/_officer/officer.verify'
import { Route as OpsOpsIndexRouteImport } from './routes/_ops/ops.index'
import { Route as OpsOpsBuyersRouteImport } from './routes/_ops/ops.buyers'
import { Route as OpsOpsCatalogueRouteImport } from './routes/_ops/ops.catalogue'
import { Route as OpsOpsTowerRouteImport } from './routes/_ops/ops.tower'
import { Route as OpsOpsVillagesRouteImport } from './routes/_ops/ops.villages'
import { Route as FarmerFarmEquipmentIndexRouteImport } from './routes/_farmer/farm.equipment.index'
import { Route as FarmerFarmEquipmentEquipmentIdRouteImport } from './routes/_farmer/farm.equipment.$equipmentId'
import { Route as FarmerFarmRequestsIndexRouteImport } from './routes/_farmer/farm.requests.index'
import { Route as FarmerFarmRequestsRequestIdRouteImport } from './routes/_farmer/farm.requests.$requestId'
import { Route as FarmerFarmSurveysIndexRouteImport } from './routes/_farmer/farm.surveys.index'
import { Route as FarmerFarmSurveysSurveyIdRouteImport } from './routes/_farmer/farm.surveys.$surveyId'
import { Route as OfficerOfficerCyclesCycleIdRouteImport } from './routes/_officer/officer.cycles.$cycleId'
import { Route as OfficerOfficerFarmsFarmIdRouteImport } from './routes/_officer/officer.farms.$farmId'
import { Route as OfficerOfficerPeopleIndexRouteImport } from './routes/_officer/officer.people.index'
import { Route as OfficerOfficerPeoplePersonIdRouteImport } from './routes/_officer/officer.people.$personId'
import { Route as OpsOpsDemandIndexRouteImport } from './routes/_ops/ops.demand.index'
import { Route as OpsOpsDemandDemandIdRouteImport } from './routes/_ops/ops.demand.$demandId'
import { Route as OpsOpsOpportunitiesOpportunityIdRouteImport } from './routes/_ops/ops.opportunities.$opportunityId'
import { Route as OpsOpsRequestsIndexRouteImport } from './routes/_ops/ops.requests.index'
import { Route as OpsOpsRequestsRequestIdRouteImport } from './routes/_ops/ops.requests.$requestId'
import { Route as OpsOpsSurveysIndexRouteImport } from './routes/_ops/ops.surveys.index'
import { Route as OpsOpsSurveysSurveyIdRouteImport } from './routes/_ops/ops.surveys.$surveyId'
import { Route as OpsOpsSurveysRedemptionsRouteImport } from './routes/_ops/ops.surveys.redemptions'
import { Route as OpsOpsTowerIndexRouteImport } from './routes/_ops/ops.tower.index'
import { Route as OpsOpsTowerEnergyRouteImport } from './routes/_ops/ops.tower.energy'
import { Route as OpsOpsTowerMarketRouteImport } from './routes/_ops/ops.tower.market'
import { Route as OpsOpsTowerProductionRouteImport } from './routes/_ops/ops.tower.production'
import { Route as OpsOpsTowerQualityRouteImport } from './routes/_ops/ops.tower.quality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/_farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/_officer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authNoAccessRoute = authNoAccessRouteImport.update({
  id: '/(auth)/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const authSelectRoleRoute = authSelectRoleRouteImport.update({
  id: '/(auth)/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetPasswordRoute = authSetPasswordRouteImport.update({
  id: '/(auth)/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerFarmRoute = FarmerFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => FarmerRoute,
} as any)
const OfficerOfficerRoute = OfficerOfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => OfficerRoute,
} as any)
const OpsOpsRoute = OpsOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => OpsRoute,
} as any)
const FarmerFarmIndexRoute = FarmerFarmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerFarmRoute,
} as any)
const FarmerFarmMyFarmRoute = FarmerFarmMyFarmRouteImport.update({
  id: '/my-farm',
  path: '/my-farm',
  getParentRoute: () => FarmerFarmRoute,
} as any)
const FarmerFarmOpportunitiesRoute = FarmerFarmOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => FarmerFarmRoute,
} as any)
const OfficerOfficerIndexRoute = OfficerOfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerOfficerRoute,
} as any)
const OfficerOfficerRedeemRoute = OfficerOfficerRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => OfficerOfficerRoute,
} as any)
const OfficerOfficerRegisterRoute = OfficerOfficerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => OfficerOfficerRoute,
} as any)
const OfficerOfficerVerifyRoute = OfficerOfficerVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => OfficerOfficerRoute,
} as any)
const OpsOpsIndexRoute = OpsOpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsBuyersRoute = OpsOpsBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsCatalogueRoute = OpsOpsCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsTowerRoute = OpsOpsTowerRouteImport.update({
  id: '/tower',
  path: '/tower',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsVillagesRoute = OpsOpsVillagesRouteImport.update({
  id: '/villages',
  path: '/villages',
  getParentRoute: () => OpsOpsRoute,
} as any)
const FarmerFarmEquipmentIndexRoute =
  FarmerFarmEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => FarmerFarmRoute,
  } as any)
const FarmerFarmEquipmentEquipmentIdRoute =
  FarmerFarmEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => FarmerFarmRoute,
  } as any)
const FarmerFarmRequestsIndexRoute = FarmerFarmRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => FarmerFarmRoute,
} as any)
const FarmerFarmRequestsRequestIdRoute =
  FarmerFarmRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => FarmerFarmRoute,
  } as any)
const FarmerFarmSurveysIndexRoute = FarmerFarmSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => FarmerFarmRoute,
} as any)
const FarmerFarmSurveysSurveyIdRoute =
  FarmerFarmSurveysSurveyIdRouteImport.update({
    id: '/surveys/$surveyId',
    path: '/surveys/$surveyId',
    getParentRoute: () => FarmerFarmRoute,
  } as any)
const OfficerOfficerCyclesCycleIdRoute =
  OfficerOfficerCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => OfficerOfficerRoute,
  } as any)
const OfficerOfficerFarmsFarmIdRoute =
  OfficerOfficerFarmsFarmIdRouteImport.update({
    id: '/farms/$farmId',
    path: '/farms/$farmId',
    getParentRoute: () => OfficerOfficerRoute,
  } as any)
const OfficerOfficerPeopleIndexRoute =
  OfficerOfficerPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => OfficerOfficerRoute,
  } as any)
const OfficerOfficerPeoplePersonIdRoute =
  OfficerOfficerPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => OfficerOfficerRoute,
  } as any)
const OpsOpsDemandIndexRoute = OpsOpsDemandIndexRouteImport.update({
  id: '/demand/',
  path: '/demand/',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsDemandDemandIdRoute = OpsOpsDemandDemandIdRouteImport.update({
  id: '/demand/$demandId',
  path: '/demand/$demandId',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsOpportunitiesOpportunityIdRoute =
  OpsOpsOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => OpsOpsRoute,
  } as any)
const OpsOpsRequestsIndexRoute = OpsOpsRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsRequestsRequestIdRoute = OpsOpsRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsSurveysIndexRoute = OpsOpsSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsSurveysSurveyIdRoute = OpsOpsSurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsSurveysRedemptionsRoute =
  OpsOpsSurveysRedemptionsRouteImport.update({
    id: '/surveys/redemptions',
    path: '/surveys/redemptions',
    getParentRoute: () => OpsOpsRoute,
  } as any)
const OpsOpsTowerIndexRoute = OpsOpsTowerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsOpsTowerRoute,
} as any)
const OpsOpsTowerEnergyRoute = OpsOpsTowerEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => OpsOpsTowerRoute,
} as any)
const OpsOpsTowerMarketRoute = OpsOpsTowerMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => OpsOpsTowerRoute,
} as any)
const OpsOpsTowerProductionRoute = OpsOpsTowerProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => OpsOpsTowerRoute,
} as any)
const OpsOpsTowerQualityRoute = OpsOpsTowerQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => OpsOpsTowerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/no-access': typeof authNoAccessRoute
  '/select-role': typeof authSelectRoleRoute
  '/set-password': typeof authSetPasswordRoute
  '/farm': typeof FarmerFarmRouteWithChildren
  '/officer': typeof OfficerOfficerRouteWithChildren
  '/ops': typeof OpsOpsRouteWithChildren
  '/farm/my-farm': typeof FarmerFarmMyFarmRoute
  '/farm/opportunities': typeof FarmerFarmOpportunitiesRoute
  '/officer/redeem': typeof OfficerOfficerRedeemRoute
  '/officer/register': typeof OfficerOfficerRegisterRoute
  '/officer/verify': typeof OfficerOfficerVerifyRoute
  '/ops/buyers': typeof OpsOpsBuyersRoute
  '/ops/catalogue': typeof OpsOpsCatalogueRoute
  '/ops/tower': typeof OpsOpsTowerRouteWithChildren
  '/ops/villages': typeof OpsOpsVillagesRoute
  '/farm/': typeof FarmerFarmIndexRoute
  '/officer/': typeof OfficerOfficerIndexRoute
  '/ops/': typeof OpsOpsIndexRoute
  '/farm/equipment/$equipmentId': typeof FarmerFarmEquipmentEquipmentIdRoute
  '/farm/requests/$requestId': typeof FarmerFarmRequestsRequestIdRoute
  '/farm/surveys/$surveyId': typeof FarmerFarmSurveysSurveyIdRoute
  '/officer/cycles/$cycleId': typeof OfficerOfficerCyclesCycleIdRoute
  '/officer/farms/$farmId': typeof OfficerOfficerFarmsFarmIdRoute
  '/officer/people/$personId': typeof OfficerOfficerPeoplePersonIdRoute
  '/ops/demand/$demandId': typeof OpsOpsDemandDemandIdRoute
  '/ops/opportunities/$opportunityId': typeof OpsOpsOpportunitiesOpportunityIdRoute
  '/ops/requests/$requestId': typeof OpsOpsRequestsRequestIdRoute
  '/ops/surveys/$surveyId': typeof OpsOpsSurveysSurveyIdRoute
  '/ops/surveys/redemptions': typeof OpsOpsSurveysRedemptionsRoute
  '/ops/tower/energy': typeof OpsOpsTowerEnergyRoute
  '/ops/tower/market': typeof OpsOpsTowerMarketRoute
  '/ops/tower/production': typeof OpsOpsTowerProductionRoute
  '/ops/tower/quality': typeof OpsOpsTowerQualityRoute
  '/farm/equipment/': typeof FarmerFarmEquipmentIndexRoute
  '/farm/requests/': typeof FarmerFarmRequestsIndexRoute
  '/farm/surveys/': typeof FarmerFarmSurveysIndexRoute
  '/officer/people/': typeof OfficerOfficerPeopleIndexRoute
  '/ops/demand/': typeof OpsOpsDemandIndexRoute
  '/ops/requests/': typeof OpsOpsRequestsIndexRoute
  '/ops/surveys/': typeof OpsOpsSurveysIndexRoute
  '/ops/tower/': typeof OpsOpsTowerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/no-access': typeof authNoAccessRoute
  '/select-role': typeof authSelectRoleRoute
  '/set-password': typeof authSetPasswordRoute
  '/farm/my-farm': typeof FarmerFarmMyFarmRoute
  '/farm/opportunities': typeof FarmerFarmOpportunitiesRoute
  '/officer/redeem': typeof OfficerOfficerRedeemRoute
  '/officer/register': typeof OfficerOfficerRegisterRoute
  '/officer/verify': typeof OfficerOfficerVerifyRoute
  '/ops/buyers': typeof OpsOpsBuyersRoute
  '/ops/catalogue': typeof OpsOpsCatalogueRoute
  '/ops/villages': typeof OpsOpsVillagesRoute
  '/farm': typeof FarmerFarmIndexRoute
  '/officer': typeof OfficerOfficerIndexRoute
  '/ops': typeof OpsOpsIndexRoute
  '/farm/equipment/$equipmentId': typeof FarmerFarmEquipmentEquipmentIdRoute
  '/farm/requests/$requestId': typeof FarmerFarmRequestsRequestIdRoute
  '/farm/surveys/$surveyId': typeof FarmerFarmSurveysSurveyIdRoute
  '/officer/cycles/$cycleId': typeof OfficerOfficerCyclesCycleIdRoute
  '/officer/farms/$farmId': typeof OfficerOfficerFarmsFarmIdRoute
  '/officer/people/$personId': typeof OfficerOfficerPeoplePersonIdRoute
  '/ops/demand/$demandId': typeof OpsOpsDemandDemandIdRoute
  '/ops/opportunities/$opportunityId': typeof OpsOpsOpportunitiesOpportunityIdRoute
  '/ops/requests/$requestId': typeof OpsOpsRequestsRequestIdRoute
  '/ops/surveys/$surveyId': typeof OpsOpsSurveysSurveyIdRoute
  '/ops/surveys/redemptions': typeof OpsOpsSurveysRedemptionsRoute
  '/ops/tower/energy': typeof OpsOpsTowerEnergyRoute
  '/ops/tower/market': typeof OpsOpsTowerMarketRoute
  '/ops/tower/production': typeof OpsOpsTowerProductionRoute
  '/ops/tower/quality': typeof OpsOpsTowerQualityRoute
  '/farm/equipment': typeof FarmerFarmEquipmentIndexRoute
  '/farm/requests': typeof FarmerFarmRequestsIndexRoute
  '/farm/surveys': typeof FarmerFarmSurveysIndexRoute
  '/officer/people': typeof OfficerOfficerPeopleIndexRoute
  '/ops/demand': typeof OpsOpsDemandIndexRoute
  '/ops/requests': typeof OpsOpsRequestsIndexRoute
  '/ops/surveys': typeof OpsOpsSurveysIndexRoute
  '/ops/tower': typeof OpsOpsTowerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_farmer': typeof FarmerRouteWithChildren
  '/_officer': typeof OfficerRouteWithChildren
  '/_ops': typeof OpsRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/no-access': typeof authNoAccessRoute
  '/(auth)/select-role': typeof authSelectRoleRoute
  '/(auth)/set-password': typeof authSetPasswordRoute
  '/_farmer/farm': typeof FarmerFarmRouteWithChildren
  '/_officer/officer': typeof OfficerOfficerRouteWithChildren
  '/_ops/ops': typeof OpsOpsRouteWithChildren
  '/_farmer/farm/my-farm': typeof FarmerFarmMyFarmRoute
  '/_farmer/farm/opportunities': typeof FarmerFarmOpportunitiesRoute
  '/_officer/officer/redeem': typeof OfficerOfficerRedeemRoute
  '/_officer/officer/register': typeof OfficerOfficerRegisterRoute
  '/_officer/officer/verify': typeof OfficerOfficerVerifyRoute
  '/_ops/ops/buyers': typeof OpsOpsBuyersRoute
  '/_ops/ops/catalogue': typeof OpsOpsCatalogueRoute
  '/_ops/ops/tower': typeof OpsOpsTowerRouteWithChildren
  '/_ops/ops/villages': typeof OpsOpsVillagesRoute
  '/_farmer/farm/': typeof FarmerFarmIndexRoute
  '/_officer/officer/': typeof OfficerOfficerIndexRoute
  '/_ops/ops/': typeof OpsOpsIndexRoute
  '/_farmer/farm/equipment/$equipmentId': typeof FarmerFarmEquipmentEquipmentIdRoute
  '/_farmer/farm/requests/$requestId': typeof FarmerFarmRequestsRequestIdRoute
  '/_farmer/farm/surveys/$surveyId': typeof FarmerFarmSurveysSurveyIdRoute
  '/_officer/officer/cycles/$cycleId': typeof OfficerOfficerCyclesCycleIdRoute
  '/_officer/officer/farms/$farmId': typeof OfficerOfficerFarmsFarmIdRoute
  '/_officer/officer/people/$personId': typeof OfficerOfficerPeoplePersonIdRoute
  '/_ops/ops/demand/$demandId': typeof OpsOpsDemandDemandIdRoute
  '/_ops/ops/opportunities/$opportunityId': typeof OpsOpsOpportunitiesOpportunityIdRoute
  '/_ops/ops/requests/$requestId': typeof OpsOpsRequestsRequestIdRoute
  '/_ops/ops/surveys/$surveyId': typeof OpsOpsSurveysSurveyIdRoute
  '/_ops/ops/surveys/redemptions': typeof OpsOpsSurveysRedemptionsRoute
  '/_ops/ops/tower/energy': typeof OpsOpsTowerEnergyRoute
  '/_ops/ops/tower/market': typeof OpsOpsTowerMarketRoute
  '/_ops/ops/tower/production': typeof OpsOpsTowerProductionRoute
  '/_ops/ops/tower/quality': typeof OpsOpsTowerQualityRoute
  '/_farmer/farm/equipment/': typeof FarmerFarmEquipmentIndexRoute
  '/_farmer/farm/requests/': typeof FarmerFarmRequestsIndexRoute
  '/_farmer/farm/surveys/': typeof FarmerFarmSurveysIndexRoute
  '/_officer/officer/people/': typeof OfficerOfficerPeopleIndexRoute
  '/_ops/ops/demand/': typeof OpsOpsDemandIndexRoute
  '/_ops/ops/requests/': typeof OpsOpsRequestsIndexRoute
  '/_ops/ops/surveys/': typeof OpsOpsSurveysIndexRoute
  '/_ops/ops/tower/': typeof OpsOpsTowerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/select-role'
    | '/set-password'
    | '/farm'
    | '/officer'
    | '/ops'
    | '/farm/my-farm'
    | '/farm/opportunities'
    | '/officer/redeem'
    | '/officer/register'
    | '/officer/verify'
    | '/ops/buyers'
    | '/ops/catalogue'
    | '/ops/tower'
    | '/ops/villages'
    | '/farm/'
    | '/officer/'
    | '/ops/'
    | '/farm/equipment/$equipmentId'
    | '/farm/requests/$requestId'
    | '/farm/surveys/$surveyId'
    | '/officer/cycles/$cycleId'
    | '/officer/farms/$farmId'
    | '/officer/people/$personId'
    | '/ops/demand/$demandId'
    | '/ops/opportunities/$opportunityId'
    | '/ops/requests/$requestId'
    | '/ops/surveys/$surveyId'
    | '/ops/surveys/redemptions'
    | '/ops/tower/energy'
    | '/ops/tower/market'
    | '/ops/tower/production'
    | '/ops/tower/quality'
    | '/farm/equipment/'
    | '/farm/requests/'
    | '/farm/surveys/'
    | '/officer/people/'
    | '/ops/demand/'
    | '/ops/requests/'
    | '/ops/surveys/'
    | '/ops/tower/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/select-role'
    | '/set-password'
    | '/farm/my-farm'
    | '/farm/opportunities'
    | '/officer/redeem'
    | '/officer/register'
    | '/officer/verify'
    | '/ops/buyers'
    | '/ops/catalogue'
    | '/ops/villages'
    | '/farm'
    | '/officer'
    | '/ops'
    | '/farm/equipment/$equipmentId'
    | '/farm/requests/$requestId'
    | '/farm/surveys/$surveyId'
    | '/officer/cycles/$cycleId'
    | '/officer/farms/$farmId'
    | '/officer/people/$personId'
    | '/ops/demand/$demandId'
    | '/ops/opportunities/$opportunityId'
    | '/ops/requests/$requestId'
    | '/ops/surveys/$surveyId'
    | '/ops/surveys/redemptions'
    | '/ops/tower/energy'
    | '/ops/tower/market'
    | '/ops/tower/production'
    | '/ops/tower/quality'
    | '/farm/equipment'
    | '/farm/requests'
    | '/farm/surveys'
    | '/officer/people'
    | '/ops/demand'
    | '/ops/requests'
    | '/ops/surveys'
    | '/ops/tower'
  id:
    | '__root__'
    | '/'
    | '/_farmer'
    | '/_officer'
    | '/_ops'
    | '/(auth)/login'
    | '/(auth)/no-access'
    | '/(auth)/select-role'
    | '/(auth)/set-password'
    | '/_farmer/farm'
    | '/_officer/officer'
    | '/_ops/ops'
    | '/_farmer/farm/my-farm'
    | '/_farmer/farm/opportunities'
    | '/_officer/officer/redeem'
    | '/_officer/officer/register'
    | '/_officer/officer/verify'
    | '/_ops/ops/buyers'
    | '/_ops/ops/catalogue'
    | '/_ops/ops/tower'
    | '/_ops/ops/villages'
    | '/_farmer/farm/'
    | '/_officer/officer/'
    | '/_ops/ops/'
    | '/_farmer/farm/equipment/$equipmentId'
    | '/_farmer/farm/requests/$requestId'
    | '/_farmer/farm/surveys/$surveyId'
    | '/_officer/officer/cycles/$cycleId'
    | '/_officer/officer/farms/$farmId'
    | '/_officer/officer/people/$personId'
    | '/_ops/ops/demand/$demandId'
    | '/_ops/ops/opportunities/$opportunityId'
    | '/_ops/ops/requests/$requestId'
    | '/_ops/ops/surveys/$surveyId'
    | '/_ops/ops/surveys/redemptions'
    | '/_ops/ops/tower/energy'
    | '/_ops/ops/tower/market'
    | '/_ops/ops/tower/production'
    | '/_ops/ops/tower/quality'
    | '/_farmer/farm/equipment/'
    | '/_farmer/farm/requests/'
    | '/_farmer/farm/surveys/'
    | '/_officer/officer/people/'
    | '/_ops/ops/demand/'
    | '/_ops/ops/requests/'
    | '/_ops/ops/surveys/'
    | '/_ops/ops/tower/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authNoAccessRoute: typeof authNoAccessRoute
  authSelectRoleRoute: typeof authSelectRoleRoute
  authSetPasswordRoute: typeof authSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_farmer': {
      id: '/_farmer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_officer': {
      id: '/_officer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/no-access': {
      id: '/(auth)/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof authNoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/select-role': {
      id: '/(auth)/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof authSelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/set-password': {
      id: '/(auth)/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof authSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_farmer/farm': {
      id: '/_farmer/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmerFarmRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/_officer/officer': {
      id: '/_officer/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerOfficerRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/_ops/ops': {
      id: '/_ops/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsOpsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_farmer/farm/': {
      id: '/_farmer/farm/'
      path: '/'
      fullPath: '/farm/'
      preLoaderRoute: typeof FarmerFarmIndexRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/my-farm': {
      id: '/_farmer/farm/my-farm'
      path: '/my-farm'
      fullPath: '/farm/my-farm'
      preLoaderRoute: typeof FarmerFarmMyFarmRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/opportunities': {
      id: '/_farmer/farm/opportunities'
      path: '/opportunities'
      fullPath: '/farm/opportunities'
      preLoaderRoute: typeof FarmerFarmOpportunitiesRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_officer/officer/': {
      id: '/_officer/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerOfficerIndexRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_officer/officer/redeem': {
      id: '/_officer/officer/redeem'
      path: '/redeem'
      fullPath: '/officer/redeem'
      preLoaderRoute: typeof OfficerOfficerRedeemRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_officer/officer/register': {
      id: '/_officer/officer/register'
      path: '/register'
      fullPath: '/officer/register'
      preLoaderRoute: typeof OfficerOfficerRegisterRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_officer/officer/verify': {
      id: '/_officer/officer/verify'
      path: '/verify'
      fullPath: '/officer/verify'
      preLoaderRoute: typeof OfficerOfficerVerifyRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_ops/ops/': {
      id: '/_ops/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsOpsIndexRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/buyers': {
      id: '/_ops/ops/buyers'
      path: '/buyers'
      fullPath: '/ops/buyers'
      preLoaderRoute: typeof OpsOpsBuyersRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/catalogue': {
      id: '/_ops/ops/catalogue'
      path: '/catalogue'
      fullPath: '/ops/catalogue'
      preLoaderRoute: typeof OpsOpsCatalogueRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/tower': {
      id: '/_ops/ops/tower'
      path: '/tower'
      fullPath: '/ops/tower'
      preLoaderRoute: typeof OpsOpsTowerRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/villages': {
      id: '/_ops/ops/villages'
      path: '/villages'
      fullPath: '/ops/villages'
      preLoaderRoute: typeof OpsOpsVillagesRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_farmer/farm/equipment/': {
      id: '/_farmer/farm/equipment/'
      path: '/equipment'
      fullPath: '/farm/equipment/'
      preLoaderRoute: typeof FarmerFarmEquipmentIndexRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/equipment/$equipmentId': {
      id: '/_farmer/farm/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/farm/equipment/$equipmentId'
      preLoaderRoute: typeof FarmerFarmEquipmentEquipmentIdRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/requests/': {
      id: '/_farmer/farm/requests/'
      path: '/requests'
      fullPath: '/farm/requests/'
      preLoaderRoute: typeof FarmerFarmRequestsIndexRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/requests/$requestId': {
      id: '/_farmer/farm/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/farm/requests/$requestId'
      preLoaderRoute: typeof FarmerFarmRequestsRequestIdRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/surveys/': {
      id: '/_farmer/farm/surveys/'
      path: '/surveys'
      fullPath: '/farm/surveys/'
      preLoaderRoute: typeof FarmerFarmSurveysIndexRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_farmer/farm/surveys/$surveyId': {
      id: '/_farmer/farm/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/farm/surveys/$surveyId'
      preLoaderRoute: typeof FarmerFarmSurveysSurveyIdRouteImport
      parentRoute: typeof FarmerFarmRoute
    }
    '/_officer/officer/cycles/$cycleId': {
      id: '/_officer/officer/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/officer/cycles/$cycleId'
      preLoaderRoute: typeof OfficerOfficerCyclesCycleIdRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_officer/officer/farms/$farmId': {
      id: '/_officer/officer/farms/$farmId'
      path: '/farms/$farmId'
      fullPath: '/officer/farms/$farmId'
      preLoaderRoute: typeof OfficerOfficerFarmsFarmIdRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_officer/officer/people/': {
      id: '/_officer/officer/people/'
      path: '/people'
      fullPath: '/officer/people/'
      preLoaderRoute: typeof OfficerOfficerPeopleIndexRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_officer/officer/people/$personId': {
      id: '/_officer/officer/people/$personId'
      path: '/people/$personId'
      fullPath: '/officer/people/$personId'
      preLoaderRoute: typeof OfficerOfficerPeoplePersonIdRouteImport
      parentRoute: typeof OfficerOfficerRoute
    }
    '/_ops/ops/demand/': {
      id: '/_ops/ops/demand/'
      path: '/demand'
      fullPath: '/ops/demand/'
      preLoaderRoute: typeof OpsOpsDemandIndexRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/demand/$demandId': {
      id: '/_ops/ops/demand/$demandId'
      path: '/demand/$demandId'
      fullPath: '/ops/demand/$demandId'
      preLoaderRoute: typeof OpsOpsDemandDemandIdRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/opportunities/$opportunityId': {
      id: '/_ops/ops/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/ops/opportunities/$opportunityId'
      preLoaderRoute: typeof OpsOpsOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/requests/': {
      id: '/_ops/ops/requests/'
      path: '/requests'
      fullPath: '/ops/requests/'
      preLoaderRoute: typeof OpsOpsRequestsIndexRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/requests/$requestId': {
      id: '/_ops/ops/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/ops/requests/$requestId'
      preLoaderRoute: typeof OpsOpsRequestsRequestIdRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/surveys/': {
      id: '/_ops/ops/surveys/'
      path: '/surveys'
      fullPath: '/ops/surveys/'
      preLoaderRoute: typeof OpsOpsSurveysIndexRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/surveys/$surveyId': {
      id: '/_ops/ops/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/ops/surveys/$surveyId'
      preLoaderRoute: typeof OpsOpsSurveysSurveyIdRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/surveys/redemptions': {
      id: '/_ops/ops/surveys/redemptions'
      path: '/surveys/redemptions'
      fullPath: '/ops/surveys/redemptions'
      preLoaderRoute: typeof OpsOpsSurveysRedemptionsRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/tower/': {
      id: '/_ops/ops/tower/'
      path: '/'
      fullPath: '/ops/tower/'
      preLoaderRoute: typeof OpsOpsTowerIndexRouteImport
      parentRoute: typeof OpsOpsTowerRoute
    }
    '/_ops/ops/tower/energy': {
      id: '/_ops/ops/tower/energy'
      path: '/energy'
      fullPath: '/ops/tower/energy'
      preLoaderRoute: typeof OpsOpsTowerEnergyRouteImport
      parentRoute: typeof OpsOpsTowerRoute
    }
    '/_ops/ops/tower/market': {
      id: '/_ops/ops/tower/market'
      path: '/market'
      fullPath: '/ops/tower/market'
      preLoaderRoute: typeof OpsOpsTowerMarketRouteImport
      parentRoute: typeof OpsOpsTowerRoute
    }
    '/_ops/ops/tower/production': {
      id: '/_ops/ops/tower/production'
      path: '/production'
      fullPath: '/ops/tower/production'
      preLoaderRoute: typeof OpsOpsTowerProductionRouteImport
      parentRoute: typeof OpsOpsTowerRoute
    }
    '/_ops/ops/tower/quality': {
      id: '/_ops/ops/tower/quality'
      path: '/quality'
      fullPath: '/ops/tower/quality'
      preLoaderRoute: typeof OpsOpsTowerQualityRouteImport
      parentRoute: typeof OpsOpsTowerRoute
    }
  }
}

interface FarmerFarmRouteChildren {
  FarmerFarmMyFarmRoute: typeof FarmerFarmMyFarmRoute
  FarmerFarmOpportunitiesRoute: typeof FarmerFarmOpportunitiesRoute
  FarmerFarmIndexRoute: typeof FarmerFarmIndexRoute
  FarmerFarmEquipmentEquipmentIdRoute: typeof FarmerFarmEquipmentEquipmentIdRoute
  FarmerFarmRequestsRequestIdRoute: typeof FarmerFarmRequestsRequestIdRoute
  FarmerFarmSurveysSurveyIdRoute: typeof FarmerFarmSurveysSurveyIdRoute
  FarmerFarmEquipmentIndexRoute: typeof FarmerFarmEquipmentIndexRoute
  FarmerFarmRequestsIndexRoute: typeof FarmerFarmRequestsIndexRoute
  FarmerFarmSurveysIndexRoute: typeof FarmerFarmSurveysIndexRoute
}

const FarmerFarmRouteChildren: FarmerFarmRouteChildren = {
  FarmerFarmMyFarmRoute: FarmerFarmMyFarmRoute,
  FarmerFarmOpportunitiesRoute: FarmerFarmOpportunitiesRoute,
  FarmerFarmIndexRoute: FarmerFarmIndexRoute,
  FarmerFarmEquipmentEquipmentIdRoute: FarmerFarmEquipmentEquipmentIdRoute,
  FarmerFarmRequestsRequestIdRoute: FarmerFarmRequestsRequestIdRoute,
  FarmerFarmSurveysSurveyIdRoute: FarmerFarmSurveysSurveyIdRoute,
  FarmerFarmEquipmentIndexRoute: FarmerFarmEquipmentIndexRoute,
  FarmerFarmRequestsIndexRoute: FarmerFarmRequestsIndexRoute,
  FarmerFarmSurveysIndexRoute: FarmerFarmSurveysIndexRoute,
}

const FarmerFarmRouteWithChildren = FarmerFarmRoute._addFileChildren(
  FarmerFarmRouteChildren,
)

interface FarmerRouteChildren {
  FarmerFarmRoute: typeof FarmerFarmRouteWithChildren
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerFarmRoute: FarmerFarmRouteWithChildren,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface OfficerOfficerRouteChildren {
  OfficerOfficerRedeemRoute: typeof OfficerOfficerRedeemRoute
  OfficerOfficerRegisterRoute: typeof OfficerOfficerRegisterRoute
  OfficerOfficerVerifyRoute: typeof OfficerOfficerVerifyRoute
  OfficerOfficerIndexRoute: typeof OfficerOfficerIndexRoute
  OfficerOfficerCyclesCycleIdRoute: typeof OfficerOfficerCyclesCycleIdRoute
  OfficerOfficerFarmsFarmIdRoute: typeof OfficerOfficerFarmsFarmIdRoute
  OfficerOfficerPeoplePersonIdRoute: typeof OfficerOfficerPeoplePersonIdRoute
  OfficerOfficerPeopleIndexRoute: typeof OfficerOfficerPeopleIndexRoute
}

const OfficerOfficerRouteChildren: OfficerOfficerRouteChildren = {
  OfficerOfficerRedeemRoute: OfficerOfficerRedeemRoute,
  OfficerOfficerRegisterRoute: OfficerOfficerRegisterRoute,
  OfficerOfficerVerifyRoute: OfficerOfficerVerifyRoute,
  OfficerOfficerIndexRoute: OfficerOfficerIndexRoute,
  OfficerOfficerCyclesCycleIdRoute: OfficerOfficerCyclesCycleIdRoute,
  OfficerOfficerFarmsFarmIdRoute: OfficerOfficerFarmsFarmIdRoute,
  OfficerOfficerPeoplePersonIdRoute: OfficerOfficerPeoplePersonIdRoute,
  OfficerOfficerPeopleIndexRoute: OfficerOfficerPeopleIndexRoute,
}

const OfficerOfficerRouteWithChildren = OfficerOfficerRoute._addFileChildren(
  OfficerOfficerRouteChildren,
)

interface OfficerRouteChildren {
  OfficerOfficerRoute: typeof OfficerOfficerRouteWithChildren
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerOfficerRoute: OfficerOfficerRouteWithChildren,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface OpsOpsTowerRouteChildren {
  OpsOpsTowerEnergyRoute: typeof OpsOpsTowerEnergyRoute
  OpsOpsTowerMarketRoute: typeof OpsOpsTowerMarketRoute
  OpsOpsTowerProductionRoute: typeof OpsOpsTowerProductionRoute
  OpsOpsTowerQualityRoute: typeof OpsOpsTowerQualityRoute
  OpsOpsTowerIndexRoute: typeof OpsOpsTowerIndexRoute
}

const OpsOpsTowerRouteChildren: OpsOpsTowerRouteChildren = {
  OpsOpsTowerEnergyRoute: OpsOpsTowerEnergyRoute,
  OpsOpsTowerMarketRoute: OpsOpsTowerMarketRoute,
  OpsOpsTowerProductionRoute: OpsOpsTowerProductionRoute,
  OpsOpsTowerQualityRoute: OpsOpsTowerQualityRoute,
  OpsOpsTowerIndexRoute: OpsOpsTowerIndexRoute,
}

const OpsOpsTowerRouteWithChildren = OpsOpsTowerRoute._addFileChildren(
  OpsOpsTowerRouteChildren,
)

interface OpsOpsRouteChildren {
  OpsOpsBuyersRoute: typeof OpsOpsBuyersRoute
  OpsOpsCatalogueRoute: typeof OpsOpsCatalogueRoute
  OpsOpsTowerRoute: typeof OpsOpsTowerRouteWithChildren
  OpsOpsVillagesRoute: typeof OpsOpsVillagesRoute
  OpsOpsIndexRoute: typeof OpsOpsIndexRoute
  OpsOpsDemandDemandIdRoute: typeof OpsOpsDemandDemandIdRoute
  OpsOpsOpportunitiesOpportunityIdRoute: typeof OpsOpsOpportunitiesOpportunityIdRoute
  OpsOpsRequestsRequestIdRoute: typeof OpsOpsRequestsRequestIdRoute
  OpsOpsSurveysSurveyIdRoute: typeof OpsOpsSurveysSurveyIdRoute
  OpsOpsSurveysRedemptionsRoute: typeof OpsOpsSurveysRedemptionsRoute
  OpsOpsDemandIndexRoute: typeof OpsOpsDemandIndexRoute
  OpsOpsRequestsIndexRoute: typeof OpsOpsRequestsIndexRoute
  OpsOpsSurveysIndexRoute: typeof OpsOpsSurveysIndexRoute
}

const OpsOpsRouteChildren: OpsOpsRouteChildren = {
  OpsOpsBuyersRoute: OpsOpsBuyersRoute,
  OpsOpsCatalogueRoute: OpsOpsCatalogueRoute,
  OpsOpsTowerRoute: OpsOpsTowerRouteWithChildren,
  OpsOpsVillagesRoute: OpsOpsVillagesRoute,
  OpsOpsIndexRoute: OpsOpsIndexRoute,
  OpsOpsDemandDemandIdRoute: OpsOpsDemandDemandIdRoute,
  OpsOpsOpportunitiesOpportunityIdRoute: OpsOpsOpportunitiesOpportunityIdRoute,
  OpsOpsRequestsRequestIdRoute: OpsOpsRequestsRequestIdRoute,
  OpsOpsSurveysSurveyIdRoute: OpsOpsSurveysSurveyIdRoute,
  OpsOpsSurveysRedemptionsRoute: OpsOpsSurveysRedemptionsRoute,
  OpsOpsDemandIndexRoute: OpsOpsDemandIndexRoute,
  OpsOpsRequestsIndexRoute: OpsOpsRequestsIndexRoute,
  OpsOpsSurveysIndexRoute: OpsOpsSurveysIndexRoute,
}

const OpsOpsRouteWithChildren =
  OpsOpsRoute._addFileChildren(OpsOpsRouteChildren)

interface OpsRouteChildren {
  OpsOpsRoute: typeof OpsOpsRouteWithChildren
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsOpsRoute: OpsOpsRouteWithChildren,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerRoute: FarmerRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authNoAccessRoute: authNoAccessRoute,
  authSelectRoleRoute: authSelectRoleRoute,
  authSetPasswordRoute: authSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
